"use strict";
/**
 * gen-acceptance-checklist.test.js
 * Tests for the buildChecklist and renderMarkdown logic.
 */

// ---------------------------------------------------------------------------
// Inline the pure functions under test (no side-effects, no exec calls)
// ---------------------------------------------------------------------------

const RULES = [
  { pattern: /^scripts\//, items: ["Script runs without errors", "Unit test added"] },
  { pattern: /^\.github\/workflows\//, items: ["Workflow triggers are intentional"] },
  { pattern: /^docs\//, items: ["Document is reachable from an index"] },
  { pattern: /^docs\/adr\//, items: ["ADR follows the standard template"] },
  { pattern: /^(backend|frontend)\//, items: ["Unit tests added or updated"] },
  { pattern: /^soroban\//, items: ["Contract compiles"] },
];

const DEFAULT_ITEMS = [
  "Change is covered by at least one test",
  "PR description explains the _why_",
];

function buildChecklist(files) {
  const seen = new Set();
  const sections = [];
  for (const file of files) {
    for (const rule of RULES) {
      if (!rule.pattern.test(file)) continue;
      const key = rule.pattern.toString();
      if (seen.has(key)) continue;
      seen.add(key);
      sections.push({ label: "matched", items: rule.items });
    }
  }
  if (sections.length === 0) sections.push({ label: "General", items: DEFAULT_ITEMS });
  else sections.push({ label: "General", items: DEFAULT_ITEMS });
  return sections;
}

function renderMarkdown(files, sections) {
  const lines = [
    "<!-- SUGGESTION: generated by gen-acceptance-checklist.js — edit freely before submitting -->",
    "",
    "## Acceptance Checklist (suggested)",
  ];
  for (const s of sections) {
    lines.push(`### ${s.label}`);
    for (const item of s.items) lines.push(`- [ ] ${item}`);
  }
  lines.push("_This checklist is a suggestion. Remove, reorder, or add items as needed._");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Tests (no test framework needed — assert manually)
// ---------------------------------------------------------------------------

let passed = 0;
let failed = 0;

function assert(condition, msg) {
  if (condition) {
    console.log(`  ✓ ${msg}`);
    passed++;
  } else {
    console.error(`  ✗ ${msg}`);
    failed++;
  }
}

console.log("gen-acceptance-checklist tests");

// 1. No files → general section only
{
  const sections = buildChecklist([]);
  assert(sections.length === 1, "empty files → 1 section");
  assert(sections[0].label === "General", "section is General");
}

// 2. Script file → scripts section + General
{
  const sections = buildChecklist(["scripts/foo.js"]);
  assert(sections.length === 2, "script file → 2 sections");
  assert(sections[0].items.some((i) => i.includes("Script runs")), "scripts rule applied");
  assert(sections[sections.length - 1].label === "General", "General always last");
}

// 3. Multiple files in same module → rule applied once
{
  const sections = buildChecklist(["scripts/a.js", "scripts/b.js"]);
  const scriptSections = sections.filter((s) => s.items.some((i) => i.includes("Script runs")));
  assert(scriptSections.length === 1, "duplicate rule deduplicated");
}

// 4. Mixed files
{
  const sections = buildChecklist(["scripts/x.js", "backend/src/foo.ts"]);
  assert(sections.length === 3, "two rules + General = 3 sections");
}

// 5. ADR files
{
  const sections = buildChecklist(["docs/adr/0001-foo.md"]);
  const hasAdr = sections.some((s) => s.items.some((i) => i.includes("ADR follows")));
  assert(hasAdr, "ADR rule matched");
}

// 6. renderMarkdown contains suggestion comment
{
  const sections = buildChecklist(["scripts/foo.js"]);
  const md = renderMarkdown(["scripts/foo.js"], sections);
  assert(md.includes("SUGGESTION"), "output marked as suggestion");
  assert(md.includes("- [ ]"), "checkboxes present");
  assert(md.includes("edit freely"), "marked editable");
}

// 7. renderMarkdown has both section headings
{
  const sections = buildChecklist(["backend/src/foo.ts"]);
  const md = renderMarkdown(["backend/src/foo.ts"], sections);
  assert(md.includes("###"), "section headings present");
}

console.log(`\n${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
